### ISSUE TITLE
LabelLayer : possibilité de mettre une couleur de fond

### ISSUE THREAD

**Issue by Peckeno** [riatelab/cartography#34]
Bonjour,

Déjà un grand merci pour votre travail, votre package est vraiment très utile et facile d'accès. 

J'aurais une question concernant la fonction labelLayer. Est-il possible lors de l'affichage de faire apparaître un halo ou une couleur de fond derrière les caractères affichés ? Si ce n'est pas le cas, est-ce que cela est envisagé dans une version future de la fonction ?

En vous remerciant par avance pour votre réponse,
Cordialement,
Baptiste MARTIN

**Comment by rCarto** [comment]
La prochaine version du package contiendra cette fonctionnalité ainsi qu'une option de non recouvrement des labels. #35

**Comment by rCarto** [comment]
La prochaine version du package contiendra cette fonctionnalité ainsi qu'une option de non recouvrement des labels. #
