### ISSUE TITLE
propSymbolsLayer - Erreur de légende

### ISSUE THREAD

**Issue by Peckeno** [riatelab/cartography#42]
Bonjour, 
Tout d'abord merci pour votre travail.

J'ai un problème lorsque j'utilise des cartes avec la fonction propSymbolsLayer, la légende n'apparaît pas parfaitement : il y a décalage entre les cercles et les valeurs qui apparaissent à côté.
![probleme legende](https://user-images.githubusercontent.com/31700552/37782412-1bf977c2-2df3-11e8-9862-20941808cfb5.png)

Savez-vous ce qui peut poser ce genre de problèmes ?

En vous remerciant par avance,
Cordialement,

**Comment by rCarto** [comment]
Bonjour,
Oui je vois d'où vient le problème. Cela arrive quand le fond de carte n'est pas projeté. Je vais voir ce que je peux faire. 
En attendant, vous pouvez projeter le fond de carte où peut être utiliser l'argument legend.style

**Comment by Peckeno** [comment]
Merci pour cette réponse. 
J'ai changé le type de projection et cela a en effet réglé le problème.
