### ISSUE TITLE
Plot pie chart

### ISSUE THREAD

**Issue by QQ910** [riatelab/cartography#50]
Hi , I was trying to use your awesome package to pie charts with county map. IS there a way instead draw bubbles  to draw the pie chart?

**Comment by rCarto** [comment]
Hi, 
Concerning pie chart maps we roughly stand by the point of view expressed [here](https://www.businessinsider.fr/us/pie-charts-are-the-worst-2013-6) or [here](https://www.researchgate.net/publication/277648324_Multiple_Pie_Charts_Unreadable_Inefficient_and_Over-Used).
So, there is no plan to implement pie charts in `cartography`. 

If you want to display two variables on a map you could use `propTrianglesLayer()`.
