### ISSUE TITLE
histogram legend

### ISSUE THREAD

**Issue by chrijo** [riatelab/cartography#51]
Hi everybody,

first of all, I like your package very much and I'm using it for cartography purpose for while. However, I saw a nice feature in the tmap package, I hope to realize with cartography. In tmap one is able to plot a histogram (tm_fill(..., legend.hist = TRUE)) to the corresponding legend for a choropleth map (e.g. https://workshop.mhermans.net/thematic-maps-r/04_plot.html). Is it possible to do this with cartography?

**Comment by rCarto** [comment]
Hi, 
Yes, that would be a nice feature. 
I already tried something like that [here](https://rgeomatic.hypotheses.org/1086). 
I'm not sure that's the way it should be done in cartography.

**Comment by rCarto** [comment]
WIP here : https://github.com/riatelab/cartography/tree/hist

**Comment by dieghernan** [comment]
Following the WIP of @rCarto , I have been working on further develop a feature like that: https://github.com/dieghernan/cartography/blob/histv2/R/maphist.R

There is still a point on thinking if this needs to be integrated into a legend or if it can live as standalone feature. In case of integration, the problem on `legendChoro`  is that it doesn't handle real data inputs, just labels, so a call to histogram there would need major changes.

A example on how the WIP compares with 'tmap` so far:
```
library(sf)
library(tmap)
mtq <- st_read(system.file("gpkg/mtq.gpkg", package="cartography"))
mtq$chomage=mtq$CHOM/mtq$ACT
cols=carto.pal("wine.pal",4)

# TMAP OPTION--------
tm_shape(mtq) +
  tm_borders(col = 'white', lwd = 0.3) +
  tm_fill(col = 'chomage', title = 'Chomage', legend.hist = TRUE,
          palette = cols) +
  tm_legend(legend.outside = TRUE)
```
![image](https://user-images.githubusercontent.com/25656809/75619785-adeaa900-5b80-11ea-868c-eb53cf3f442c.png)

```
# CARTOGRAPHY OPTION--------
par(mar=c(0,0,0,3))
brks=as.double(pretty(mtq$chomage))
choroLayer(mtq,var="chomage", breaks = brks, col=cols,
           legend.pos="topright",
           legend.values.rnd=2)

maphist(mtq$chomage,breaks = brks,pos="right", col=cols)
```
![image](https://user-images.githubusercontent.com/25656809/75619812-face7f80-5b80-11ea-9bc8-8d8c73d4c247.png)

**Comment by dieghernan** [comment]
An attempt to integrate it:
```
library(cartography)
library(sf)
mtq <- st_read(system.file("gpkg/mtq.gpkg", package="cartography"))
# Population density
mtq$POPDENS <- 1e6 * mtq$POP / st_area(x = mtq)
par(mar = c(0.5,0.5,2,0.5))
bks <- getBreaks(mtq$POPDENS, method = "quantile", nclass = 6)
cols <- carto.pal(pal1 = "wine.pal", 6)
choroLayer(x = mtq, var = "POPDENS", breaks = bks, col = cols,
           border = NA, legend.title.txt = "Population\nDensity",
           legend.hist = TRUE) #NEW PARAMETER
layoutLayer("Testing histogram", theme = "wine.pal")
```

![image](https://user-images.githubusercontent.com/25656809/75649045-371de080-5c52-11ea-9668-587b3713151e.png)

**Comment by chrijo** [comment]
Hello @dieghernan,

thanks, both solutions look great. However, I agree with you in that the standalone Version seems more felxible. Great job!
