### ISSUE TITLE
Legend not reflecting breaks when breaks have decimals?

### ISSUE THREAD

**Issue by jefferycsauer** [riatelab/cartography#52]
Thank you so much for your wonderful package! I am really enjoying the package so far. 

I had one quick question regarding legends. If you see my screenshot, I have set 6 manual breaks, but they are not reflected in the legend. Is there something missing in my code? 

    #add choropleth layer
    choroLayer(
      x = usa, 
      var = "one",
      method = "geom",
      breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1),
      nclass= 7,
      col = carto.pal(pal1 = "blue.pal", n1 = 7),
      border = "white", 
      lwd = 0.001,
      legend.pos = "bottomright", 
      legend.title.txt = "Test name",
      add = TRUE
    )
)

**Comment by rCarto** [comment]
In `choroLayer()` you can set the number of decimals displayed in the legend with the `legend.values.rnd` argument (set to 0 by default).

**Comment by jefferycsauer** [comment]
@rCarto thank you for the rapid response! Is there a way to set labels to the legend that DO NOT correspond to teh breaks? 

For example, if I wanted to do (1,2,3,4,5,6) for each of (0,0.2,0.4,0.6,0.8,1)? 

Best,

Jeff

**Comment by rCarto** [comment]
Sure, you can use `legendChoro()` : 
``` r
library(cartography)
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.3, PROJ 4.9.3
mtq <- st_read(system.file("gpkg/mtq.gpkg", package="cartography"), quiet = T)
cols <- carto.pal("wine.pal", 6)
choroLayer(x = mtq, var = "MED", legend.pos = "n", col = cols)
legendChoro(pos = "topright", title.txt = "Legend title", 
            breaks = c(0,1,2,3,4,5,"max value"),
            col = cols, nodata = FALSE)
```

![](https://i.imgur.com/rrtcATm.png)

<sup>Created on 2019-03-26 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jefferycsauer** [comment]
@rCarto absolutely fantastic! For whatever reason your package is much more intuitive to me compared to others. Definitely going to recommend to coworkers and implement in work!

**Comment by rCarto** [comment]
Thank you!
