### ISSUE TITLE
using 'custom' colors?

### ISSUE THREAD

**Issue by jefferycsauer** [riatelab/cartography#53]
Hello again!

Quick question! Is it possible to use custom color gradients? 

For example, is it possible to set the lowest value as "white" and highest value as "dodgerblue4"?

I saw the post about using hex colors but did not have luck...

**Comment by rCarto** [comment]
This is not particularly related to `cartography`, which use whatever colors you give it. 
Anyway, I would probably use `colorRampPalette()`. 
``` r
library(cartography)
library(sf)
#> Linking to GEOS 3.5.1, GDAL 2.2.3, PROJ 4.9.3
mtq <- st_read(system.file("gpkg/mtq.gpkg", package="cartography"), quiet = T)

cols <- colorRampPalette(colors = c("white", "dodgerblue4"))(6)

choroLayer(x = mtq, var = "MED", nclass=6, method = "quantile", col = cols)
```

![](https://i.imgur.com/TOIbwXF.png)
