### ISSUE TITLE
orphaned hole, cannot find containing polygon 

### ISSUE THREAD

**Issue by yaoGithub2018** [riatelab/cartography#55]
Hi everyone.

I was trying to make a Choropleth Map by R package cartography but ran into error. Interestingly when I use ArcMap it worked out.

Here is the error message,

Error in createPolygonsComment(p) : rgeos_PolyCreateComment: orphaned hole, cannot find containing polygon for hole at index 21.

Thanks!

**Comment by rCarto** [comment]
Hello, 
Is is difficult to help you without a reproducible example (see https://reprex.tidyverse.org/articles/articles/learn-reprex.html for example).
