### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by dieghernan** [riatelab/cartography#57]
~~I have seen that `v.2.3.0` is almost ready to be released.~~ *Update: `v.2.3.0` has been released today!!*

 I approached you in the past to discuss the possibilty of including a new layer function that would plot patterns (hatched maps) on your package.

I have been working on that and I am **ready to create a pull request on that**. Note that it has been already tested on travis:

[![Build Status](https://travis-ci.com/dieghernan/cartography.svg?branch=PRlayers)](https://travis-ci.com/dieghernan/cartography)

**`hatchedLayer`**

I rename my original `patternLayer`to `hatchedLayer` as it seems to be the most extended term for this kind of maps. I missed this feature overall on the **R** environment:

- `hatchedLayer`: Plot a hatched layer with several different patterns. Suitable for b/w print maps. See [here](https://dieghernan.github.io/cartodemo/reference/hatchedLayer.html)

- `legendHatched`: Plot legend for hatched maps. See [here](https://dieghernan.github.io/cartodemo/reference/legendHatched.html)

![hatchedimage](https://dieghernan.github.io/cartodemo/reference/legendHatched-1.svg)

**`pngLayer`**

These functions allows to use a `.png` file on the back of an `sf` object. Basically, this set of functions rasterizes, geotags and adjusts the `.png` to the `bbox` of a `POLYGON/MULTIPOLYGON`:

- `getPngLayer`: Creates a `RasterBrick` object masked to an `sf` object. See [here](https://dieghernan.github.io/cartodemo/reference/getPngLayer.html)
- `pngLayer`: Wrapper of `raster::plotRGB` that would plot the output of `getPngLayer`. See [here](https://dieghernan.github.io/cartodemo/reference/pngLayer.html)

![pngRaster](https://dieghernan.github.io/cartodemo/reference/pngLayer-1.svg) 

**Files to be added**

- `/R` folder: `hatchedLayer.R, legendHatched.R, getPngLayer.R, pngLayer.R`.
- `/man` folder: `hatchedLayer.Rd, legendHatched.Rd, getPngLayer.Rd, pngLayer.Rd`.
- Update `NAMESPACE` to register the functions.
- `/inst`: Add new file on `/img/LogoMartinique.png` to run examples: 
![imgLogo](https://raw.githubusercontent.com/dieghernan/cartodemo/master/inst/img/LogoMartinique.png)

- `\inst\tinytest\`: `test_hatchedLayer.R, test_legendHatched.R, test_getPngLayer.R, test_pngLayer.R`. Coverage of 100% on new functions, see:
[![codecov](https://codecov.io/gh/dieghernan/cartography/branch/PRlayers/graph/badge.svg)](https://codecov.io/gh/dieghernan/cartography)

There is still a couple of things to be tweaked, but all can be ready by the end of this week. 

Please to receive feedback from you.

**Comment by dieghernan** [comment]
In the case that the **PR** would be accepted, next steps would be:

- [ ] Add new functions to [`/_pkgdown.yml`](https://github.com/riatelab/cartography/blob/master/_pkgdown.yml)
- [ ] Add new functions to  [`/R/Package.R`](https://github.com/riatelab/cartography/blob/master/R/Package.R)
- [ ] `roxygen2::roxygenize()`
- [ ] `pkgdown::build_reference_index()
- [ ] `pkgdown::build_reference()

**Comment by rCarto** [comment]
Wow this is very nice! And `*pngLayer()` function comes as a good surprise :-)


As you have seen, v2.3.0 is really recent, so there is no hurry, but I would be very happy to accept a PR. 
I would be glad to add documentation on these function in the vignette.

**Comment by dieghernan** [comment]
On it, I would let know, also another good surprise is coming,

By the way, speaking of `hatchedLayer`, see comments here: https://stackoverflow.com/questions/21677489/fill-geospatial-polygons-with-pattern-r/59301874#59301874

**Comment by dieghernan** [comment]
Hi! I am finishing another function named **wordcloudLayer**. It is an adaptation of `wordcloud` package by @ifellows, and it is a layer in the middle of `labelLayer` and `choroLayer`.

I used the `is_overlap` function, and basically it draws a Wordcloud using the shape of an `sf` object. See [here](https://dieghernan.github.io/cartodemo/reference/wordcloudLayer.html) a description and a potential outcome.

I am working on a extended vignette to show how this function could be useful and stunning at the same time.

![here](https://dieghernan.github.io/cartodemo/articles/newfeatures_files/figure-html/wordcloudMap-1.svg)

**Comment by rCarto** [comment]
fix by #63

**Comment by ifellows** [comment]
@dieghernan , looks cool. Thank you for providing authorship attribution.
