### ISSUE TITLE
Custom Tiles

### ISSUE THREAD

**Issue by arthurgailes** [riatelab/cartography#58]
Hello!

I'm new to the package, but wondering if there is a way for me to use a different basemap/tile than the provided types (e.g. ESRI or other OSM maps). Thank you!

**Comment by rCarto** [comment]
Hello,
This is not possible in the current version of cartography (2.3.0). 
Still, I made a test of what could be possible in the next release. 
You can test it in the cutomtiles branch (https://github.com/riatelab/cartography/tree/cutomtiles).
```r
# install the branch in dev version from github 
library(remotes)
install_github("riatelab/cartography", ref = "cutomtiles")
```

``` r
library(sf)
#> Linking to GEOS 3.7.1, GDAL 2.4.0, PROJ 5.2.0
library(cartography)
mtq <- st_read(system.file("gpkg/mtq.gpkg", 
                           package="cartography"), 
               quiet = TRUE)
# Download esri tiles
typeosm <-  list(
  src = 'esri',
  q = 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}.jpg',
  sub = NA,
  cit = 'Tiles; Esri; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012'
)
mtqESRI <- getTiles(x = mtq, type = typeosm, 
                    verbose = T, zoom = 10)
#> https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/10/469/337.jpg => /tmp/RtmpNn5p8g/esri_10_337_469.jpg
#> https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/10/469/338.jpg => /tmp/RtmpNn5p8g/esri_10_338_469.jpg
#> https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/10/469/339.jpg => /tmp/RtmpNn5p8g/esri_10_339_469.jpg
#> https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/10/470/337.jpg => /tmp/RtmpNn5p8g/esri_10_337_470.jpg
#> https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/10/470/338.jpg => /tmp/RtmpNn5p8g/esri_10_338_470.jpg
#> https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/10/470/339.jpg => /tmp/RtmpNn5p8g/esri_10_339_470.jpg
#> Zoom:10
#> Data and map tiles sources:
#> Tiles; Esri; Source: Esri, DeLorme, NAVTEQ, USGS, Intermap, iPC, NRCAN, Esri Japan, METI, Esri China (Hong Kong), Esri (Thailand), TomTom, 2012
# Plot the tiles
par(mar = c(0,0,0,0))
tilesLayer(mtqESRI)
txt <- typeosm$cit
mtext(text = txt, side = 1, line = -1, 
      adj = 0, cex = 0.7, font = 3)
```

![](https://i.imgur.com/KlrVDJ0.png)

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


Any feedback on this would be welcomed.

**Comment by arthurgailes** [comment]
Wow! This is fantastic, thank you! I'll let you know if any bugs come up.

**Comment by dieghernan** [comment]
Hi!  On top of what you mentioned, I prepared a new code of getTiles including 49 new providers, based on leaflet-js v1.9.0.

See code on ths branch:

https://github.com/dieghernan/cartography/blob/d25374b6cf85af5de5f32afc15078475b9fd066c/R/getTiles.R#L240-L486


All these providers have been tested with mtq shape


More detail of leaflet providers + demo [here](https://leaflet-extras.github.io/leaflet-providers/)

# New providers:


OpenStreetMap
OpenStreetMap.DE
OpenStreetMap.France
OpenStreetMap.HOT
OpenTopoMap
OpenMapSurfer
OpenMapSurfer.Roads
OpenMapSurfer.Hybrid
OpenMapSurfer.AdminBounds
OpenMapSurfer.ElementsAtRisk
Hydda
Hydda.Full
Hydda.Base
Hydda.RoadsAndLabels
Stamen
Stamen.Toner
Stamen.TonerBackground
Stamen.TonerHybrid
Stamen.TonerLines
Stamen.TonerLabels
Stamen.TonerLite
Stamen.Watercolor
Stamen.Terrain
Stamen.TerrainBackground
Stamen.TerrainLabels
Esri
Esri.WorldStreetMap
Esri.DeLorme
Esri.WorldTopoMap
Esri.WorldImagery
Esri.WorldTerrain
Esri.WorldShadedRelief
Esri.OceanBasemap
Esri.NatGeoWorldMap
Esri.WorldGrayCanvas
CartoDB
CartoDB.Positron
CartoDB.PositronNoLabels
CartoDB.PositronOnlyLabels
CartoDB.DarkMatter
CartoDB.DarkMatterNoLabels
CartoDB.DarkMatterOnlyLabels
CartoDB.Voyager
CartoDB.VoyagerNoLabels
CartoDB.VoyagerOnlyLabels
CartoDB.VoyagerLabelsUnder
HikeBike
HikeBike.HikeBike
Wikimedia

**Comment by dieghernan** [comment]
What is missing so far is to include these providers in the docs, I can make a proposal. 

For some other maps, specially with APIKEY requirements as Thunderforest it would be necessary to change some bits of the code, specially the part where ext is assessed.
