### ISSUE TITLE
missing corner case in cartography::getTiles

### ISSUE THREAD

**Issue by drikkes-jue** [riatelab/cartography#59]
If you call cartography::getTiles with x a a simple feature collection, which is not POINT, no bounding box bbx is generated. You should probably change
    if (nrow(x) == 1) {
        if (sf::st_is(x, "POINT")) {
to
    if (nrow(x) == 1 && sf::st_is(x, "POINT")) {

**Comment by rCarto** [comment]
Oh you're right, that's not good. Thanks!
