### ISSUE TITLE
add more methods to getBreaks

### ISSUE THREAD

**Issue by dieghernan** [riatelab/cartography#65]
I have been working on some improvements on `getBreaks`  in order to provide a full wrap of `classInt::classIntervals`, maily because I missed the options of  `pretty` on your function.

Basically, now all the methods of `classIntervals` can be used on top of your custom methods. In terms of code the change was minimal, but I needed to include as a parameter `...` to pass some options to `classIntervals`.

The main changes indeed occurs on the doc:

- References to other packages has been modified in order to make them work on `man` and pkgdown.

- `fisher-jenks` does not appear on docs, given that was an alias of `fisher`. However, the code still is backward-compatible, as `fisher-jenks`  is masked via `if (method=="fisher-jenks"){method <- "fisher"}` (unchanged).

- A couple of new examples has been added, see [here](https://dieghernan.github.io/cartodemo/reference/getBreaks.html).

I would sent a PR, however i think is a quick win.

**Comment by dieghernan** [comment]
I didn’t mention, Travis for R-devel is failing, but also prior to the change, it seems that the devel guys had done something bad... see the build of my forked master, still not updated: https://travis-ci.com/dieghernan/cartography/builds/150727411

**Comment by rCarto** [comment]
Yeah I saw that. The faulty warning is  `Warning: multiple methods tables found for ‘plot’`. To be honnest I don't understand it :-)

**Comment by dieghernan** [comment]
May be related with this change:
https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2020/03/07#n2020-03-07

Sat, 07 Mar 2020

CHANGES IN R-devel USER-VISIBLE CHANGES

The ‘plot()’ generic function is now in package ‘base’ rather than package ‘graphics’, as it is reasonable to have methods that do not use the ‘graphics’ package. The generic is currently re-exported from the ‘graphics’ namespace to allow packages importing it from there to continue working, but this may change in future versions of R.

**Comment by rCarto** [comment]
Well spotted. I only had to remove `plot()` from `graphics` imports around [here](https://github.com/riatelab/cartography/blob/d98f860d80c5936d652d478ce10fdfa7c5bf2573/R/utils.R#L332) and get rid of package cache in .travis.yml ([here](https://github.com/riatelab/cartography/blob/d98f860d80c5936d652d478ce10fdfa7c5bf2573/.travis.yml#L4)). 
The package is now only tested on devel as devel and release are now incompatible and devel is the target for pkg release...

**Comment by dieghernan** [comment]
I have made a couple of tests and I think you can still tests on `release` and `oldrel` with a couple of changes:

- Slight modification of the Travis Build Matrix, now caching only on `release` and `oldrel`
- Import the whole `graphics` `NAMESPACE`. On `oldrel` and `release` that would include `plot` without explicit mention, so it wouldn't crash on `devel`.

https://github.com/riatelab/cartography/compare/master...dieghernan:travisrelease

See link to build:

https://travis-ci.com/github/dieghernan/cartography/builds/153161959

Let me know if you want me to prepare a PR.

**Comment by rCarto** [comment]
Nice, a PR would be welcomed.
