### ISSUE TITLE
add tiles sources to getTiles

### ISSUE THREAD

**Issue by rCarto** [riatelab/cartography#74]
https://www.xyht.com/spatial-itgis/using-openstreetmap-basemaps-qgis-3-0/

**Comment by dieghernan** [comment]
Hi,

Regarding this (closed) issue, I have extracted the raw routes of https://leaflet-extras.github.io/leaflet-providers/preview/. There are some work to do, as those urls should be checked. See this folder:

https://github.com/dieghernan/cartography/tree/providers/data-raw
