### ISSUE TITLE
Facets

### ISSUE THREAD

**Issue by Edyniesky** [riatelab/cartography#76]
Hello, first I would like to congratulate you for the excellent work with the Cartography package. I would like to know if it is possible to use facets to create different maps in a single output.

**Comment by rCarto** [comment]
Thank you. 
There is no mechanism in `cartography` to create facets. 
A solution is to use `par(mfrow = c(i, j))`. This allows to create several plots in the same window/output. It will create a layout of i rows and j columns.

**Comment by Edyniesky** [comment]
Thank you very much for your help and quick response!
