### ISSUE TITLE
Add alpha channel to pngs

### ISSUE THREAD

**Issue by dieghernan** [riatelab/cartography#78]
The current implementation of `getTiles` and `getPngLayer` does not account for pngs with transparency. I have made an implementation here, basically assessing if the raw png has a fourth channel (alpha channel) and if so, replacing the RGB values for `NA` before rasterising.

 https://github.com/dieghernan/cartography/blob/646d2d502fd4f5fb5e2409ce41321120dae8e94f/R/getTiles.R#L222:L233

https://github.com/dieghernan/cartography/blob/646d2d502fd4f5fb5e2409ce41321120dae8e94f/R/getPngLayer.R#L41:L71

Check with 

```r

library(sf)
library(cartography)
  
  
  mtq <-
    st_read(system.file("gpkg/mtq.gpkg", package = "cartography"))
  mtq <- st_transform(mtq, 3857)
  mtqTerrain <- getTiles(mtq, type = "Stamen.TerrainBackground")
  mtqlabels <- getTiles(mtq, type = "CartoDB.PositronOnlyLabels")
  
  par(mar = c(0, 0, 0, 0))
  tilesLayer(mtqTerrain)
  tilesLayer(mtqlabels, add = TRUE)

```

**Comment by rCarto** [comment]
Thanks, the fix to `getTiles()` is used in `maptiles` (riatelab/maptiles#2)
