### ISSUE TITLE
Can cartography create curved road labels,  and loop base maps of different extents?

### ISSUE THREAD

**Issue by HMB3** [riatelab/cartography#84]
Hi,

Thanks for making the package, it's fantastic!

I work for a government agency in Australia, which makes many maps of political boundaries.

We need to make hundreds of maps with the same layers and symbology, but different extents.
Previously this was done in ArcMap by hand, but we want to automate the process of creating the initial maps,
which can then be edited by hand.

We are heavy R users, so if we can use Cartography instead of QGIS/Python, that would be great.

- Can we use Cartography to loop over different extents?

Also, we really need the road labels to bend with the curves in the road, as they do with the ArcMap annotation engine, EG :

![image](https://user-images.githubusercontent.com/6665861/130397099-4a4a18fb-df65-4db7-aace-0b78718b07d8.png)

![image](https://user-images.githubusercontent.com/6665861/130397222-6932027b-f925-4dd9-858f-75898da0659b.png)

![image](https://user-images.githubusercontent.com/6665861/130397253-36cc4d20-e10c-492b-bf17-adc63448eebf.png)

- Is this annotation functionality achievable in 'Cartography'?

Any advice would be greatly appreciated - I wanted to ask the experts as I haven't found an answer to this anywhere yet....

h

**Comment by rCarto** [comment]
[This question in SO](https://stackoverflow.com/questions/60086107/automatic-label-placement-for-gis-maps-in-r) addresses the same problem, unfortunately without relevant answers.
Feel free to reopen the issue if you find something.

**Comment by rCarto** [comment]
This solution is from `maptools` and for Lattice plots (not compatible with `mapsf`):
https://procomun.wordpress.com/2012/12/29/label-placement-lattice/

![image](https://user-images.githubusercontent.com/3041254/132195748-c5d47aac-057f-4950-bf01-dc0e2f0fa3b3.png)
