### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [riatelab/cartography#85]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

This package does not use retiring packages in code, so may perhaps only use them in examples or vignettes apart from for **raster**. Although I know that **mapsf** is where development is occurring, I think fixing this here isn't very burdensome.

**Comment by rCarto** [comment]
Sure, thanks for the heads up.
It's time to clean up the package a bit anyway.

**Comment by rCarto** [comment]
Should be fixed now. CRAN submission to be done as soon as possible.
